Robustness improvements for qemu booting

diff --git a/boot-image b/boot-image
--- a/boot-image
+++ b/boot-image
@@ -1,5 +1,6 @@
 #!/bin/bash
-set -euo pipefail
+set -eEuo pipefail
+export SHELLOPTS
 
 BUILDER_IMAGE=$(cat .image-name)
 
@@ -12,32 +13,52 @@ export HOST_QEMU
 # Build the helper image
 docker image build --rm --force-rm --tag ${BUILDER_IMAGE} image-builder
 
-# Get a fully resolved path to a temp dir, to work around the docker file sharing restrictions in macOS
-temp_dir=$(mktemp -d)
-temp_dir=$(cd "${temp_dir}"; pwd -P)
-trap 'rm -rf "${temp_dir}"' EXIT ERR INT TERM HUP
+#base_dir="artifacts/qemu-boot-${uuid}"
+base_dir="$(mktemp -d)"
+function _remove_basedir()
+{
+    rm -rf "${base_dir}"
+}
 
-envfile=$(mktemp "${temp_dir}"/.envfile.XXXXXX)
+function _error()
+{
+    # echo "error $?"
+    _remove_basedir
+    exit 1
+}
+
+trap _remove_basedir EXIT INT TERM HUP
+trap _error ERR
+
+mkdir -p "${base_dir}"
+base_dir="$(cd "${base_dir}"; pwd -P)" # Make sure we have a fully resolved and absolute path for docker
+if [[ "${base_dir}" == "$(pwd)" ]]; then 
+    exit 1
+fi
+
+envfile=$(mktemp "${base_dir}"/.envfile.XXXXXX)
 export -p | grep -v "DISPLAY\|HOME\|HOST=\|LS_COLORS\|PATH\|PERL\|PWD\|SHELL\|SHLVL\|SSH\|TERM\|TMPDIR\|USER=" > ${envfile}
 
 docker container run --rm -it --privileged \
                      --name rpi-boot-image-$(uuidgen) \
-                     --mount type=bind,src="${envfile}",dst=/tmp/envfile \
-                     --mount type=bind,src="${temp_dir}",dst=/work \
-                     --mount type=bind,src=$(pwd),dst=/builder \
+                     --mount type=bind,src="${envfile}",dst=/tmp/envfile,consistency=delegated \
+                     --mount type=bind,src="${base_dir}",dst=/work,consistency=delegated \
+                     --mount type=bind,src=$(pwd),dst=/builder,consistency=delegated \
                      --workdir /builder \
                      --publish 127.0.0.1:5522:5522 \
                      ${BUILDER_IMAGE} \
                      image-builder/run-image-qemu "${1}"
 
 if [[ ${HOST_QEMU} -eq 1 ]]; then
-    # Import the config created in the container and run it
-    eval "$(cat ${temp_dir}/qemu_config)"
-    pidfile="$(mktemp)"
-    image_path="${temp_dir}"/"${image_file}"
-    kernel_file="${temp_dir}"/boot/vmlinuz
-    initrd_file="${temp_dir}"/boot/initrd.img
+    source "${base_dir}"/qemu_env
+    pidfile="$(mktemp "${base_dir}"/pidfile.XXXXXX)"
+    kernel_path="${base_dir}"/"${kernel_file}"
+    initrd_path="${base_dir}"/"${initrd_file}"
+    image_path="${base_dir}"/"${image_file}"
 
-    echo ">>> Starting Pi (native qemu)"
+    source "${base_dir}"/qemu_cmd
+
+    echo ">>> Starting Pi"
+    echo "    VM base dir=${base_dir}"
     eval "${qemu_cmd}"
 fi
diff --git a/image-builder/run-image-qemu b/image-builder/run-image-qemu
--- a/image-builder/run-image-qemu
+++ b/image-builder/run-image-qemu
@@ -1,5 +1,6 @@
 #!/bin/bash
-set -euo pipefail
+set -eEuo pipefail
+export SHELLOPTS
 source image-builder/image.sh
 
 # Import host environment
@@ -8,30 +9,45 @@ if [[ -e /tmp/envfile ]]; then
 fi
 
 source_image="$1"
+IP=${IP:-}
+CIDR=${CIDR:-}
+INIT=${INIT:-}
+HOST_QEMU=${HOST_QEMU:-0}
+BACKGROUND=${BACKGROUND:-0}
 base_dir=/work
 CHROOT="${base_dir}"/chroot
 
 mkdir --parents "${CHROOT}"
 
 echo ">>> Copying image"
-export image_file=test.img
+image_file=test.img
 image_path="${base_dir}"/"${image_file}"
-cp "${source_image}" "${image_path}"
+cp --sparse=always "${source_image}" "${image_path}"
 
 echo ">>> Getting kernel files from image"
 function _clean_mount()
 {
-    unmount_chroot "${CHROOT}"
+    if [[ -n "${CHROOT:-}" ]]; then
+        unmount_chroot "${CHROOT}"
+    fi
     if [[ -n "${lodev:-}" ]]; then
         unmount_image ${lodev}
+        unset lodev
     fi
 }
+function _error()
+{
+    # echo "error $?"
+    _clean_mount
+    exit 1
+}
 trap _clean_mount EXIT INT TERM HUP
+trap _error ERR
 
 mkdir --parents "${CHROOT}"
 lodev=$(mount_image "${image_path}")
 prepare_chroot "${CHROOT}" ${lodev}
-cp -r "${CHROOT}"/boot "${base_dir}"/
+cp --recursive "${CHROOT}"/boot "${base_dir}"/
 
 echo ">>> Patching image for qemu"
 # Execute the qemu hooks
@@ -42,46 +58,63 @@ for hook in $(find qemu-hooks -maxdepth 1 -executable -type f -o -type l | sort)
         ${hook}
     ) 2>&1 | sed 's/^/    /'
 done
-trap - EXIT INT TERM HUP
+trap - ERR EXIT INT TERM HUP
 _clean_mount
+rm --recursive --force --one-file-system "${CHROOT}"
+unset CHROOT
 
 # Determine options we need to pass to qemu
-kernel_file="${base_dir}"/boot/vmlinuz
-initrd_file="${base_dir}"/boot/initrd.img
-cmdline="rw root=/dev/vda2 console=ttyAMA0 loglevel=8 rootwait fsck.repair=yes memtest=1"
-if [[ -n "${INIT:-}" ]]; then
+kernel_file="/boot/vmlinuz"
+kernel_path="${base_dir}"/"${kernel_file}"
+initrd_file="/boot/initrd.img"
+initrd_path="${base_dir}"/"${initrd_file}"
+cmdline="rw root=/dev/vda2 loglevel=8 rootwait fsck.repair=yes memtest=1"
+if [[ -n "${INIT}" ]]; then
     cmdline="${cmdline} init=${INIT}"
 fi
-export cmdline
+
+cmdline="${cmdline} console=ttyAMA0"
+
+if [[ ${BACKGROUND} -eq 1 ]]; then
+    console_opt="-daemonize -monitor none -serial file:vm_console"
+else
+    console_opt="-nographic -serial mon:stdio"
+fi
 
 # Calculate the network for qemu
 hostfwd="hostfwd=tcp:127.0.0.1:5522-:22"
-if [[ -n "${IP:-}" && -n "${CIDR:-}" ]]; then
+if [[ -n "${IP}" && -n "${CIDR}" ]]; then
     network=$(ipcalc --nocolor --nobinary ${IP}/${CIDR} | grep Network | tr '/' ' ' | awk '{print $2}')
     hostfwd="hostfwd=tcp:127.0.0.1:5522-${IP}:22,net=${network}/${CIDR}"
 fi
-export hostfwd
 
-export qemu_cmd='qemu-system-aarch64 \
+qemu_cmd='qemu-system-aarch64 \
     -name rpi \
-    -pidfile "${pidfile}" \
     -cpu cortex-a53 \
     -m 1024 \
     -machine virt \
-    -nographic \
-    -serial mon:stdio \
+    ${console_opt} \
     -netdev user,id=net0,${hostfwd} \
     -device virtio-net-device,netdev=net0 \
+    -pidfile "${pidfile}" \
     -drive file="${image_path}",format=raw,if=sd,id=hd-root \
     -device virtio-blk-device,drive=hd-root \
     -append "${cmdline}" \
-    -kernel "${kernel_file}" \
-    -initrd "${initrd_file}"'
+    -kernel "${kernel_path}" \
+    -initrd "${initrd_path}"'
 
-export -p > "${base_dir}"/qemu_config
-
-if [[ ${HOST_QEMU:-0} -eq 0 ]]; then
+if [[ ${HOST_QEMU} -eq 0 ]]; then
     echo ">>> Starting Pi"
     pidfile="$(mktemp)"
     eval "${qemu_cmd}"
+else
+    # Export the config to be run natively on the host
+    declare -p image_file >> "${base_dir}"/qemu_env
+    declare -p kernel_file >> "${base_dir}"/qemu_env
+    declare -p initrd_file >> "${base_dir}"/qemu_env
+    declare -p console_opt >> "${base_dir}"/qemu_env
+    declare -p cmdline >> "${base_dir}"/qemu_env
+    declare -p hostfwd >> "${base_dir}"/qemu_env
+
+    declare -p qemu_cmd >> "${base_dir}"/qemu_cmd
 fi
